
[package]
name = "kernelito"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
debug = false
overflow-checks = true
panic = "abort"
# opt-level=0

[dependencies]
lazy_static = {version = "1.4", features= ["spin_no_std"]}
spin = "0.5.2"
